import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { CONTACT } from '@/lib/urls';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The terms that govern use of Coldop’s cold storage management software and website.',
  alternates: { canonical: '/terms' },
};

const sections = [
  {
    heading: '1. The service',
    body: 'Coldop provides cold storage management and inventory software — gate passes, chamber stock, farmer ledgers, daybook, and reports — accessed through app.coldop.in. By creating an account or using the service you agree to these terms.',
  },
  {
    heading: '2. Accounts',
    body: 'You are responsible for the accuracy of the information you register with, for keeping your credentials safe, and for all activity under your account. Notify us immediately of any unauthorized use.',
  },
  {
    heading: '3. Your data',
    body: 'The operational records you enter — gate passes, farmer accounts, inventory, reports — belong to you. We process them only to provide the service, as described in our Privacy Policy. You can request an export of your data at any time.',
  },
  {
    heading: '4. Acceptable use',
    body: 'Do not misuse the service: no unauthorized access, no interference with other operators’ data, no use of the platform to store unlawful content, and no reselling of the service without our written consent.',
  },
  {
    heading: '5. Availability',
    body: 'We aim for high availability but do not guarantee uninterrupted service. Planned maintenance and factors outside our control (connectivity, power at your site) can affect access. Keep your own printed or exported copies of critical documents where regulation requires them.',
  },
  {
    heading: '6. Fees',
    body: 'Pricing is agreed per cold storage at onboarding. Fees, billing cycles, and any changes are communicated in advance. Non-payment after reasonable notice may lead to suspension of access; your data remains exportable.',
  },
  {
    heading: '7. Liability',
    body: 'The service is provided “as is”. To the maximum extent permitted by law, Coldop is not liable for indirect or consequential losses, including losses arising from decisions made on the basis of reports generated by the platform. Our total liability is limited to the fees paid in the twelve months before the claim.',
  },
  {
    heading: '8. Changes',
    body: 'We may update the service and these terms. Material changes are announced through the app or by email. Continued use after a change means you accept the updated terms.',
  },
  {
    heading: '9. Governing law',
    body: 'These terms are governed by the laws of India, with courts at Punjab having jurisdiction.',
  },
  {
    heading: '10. Contact',
    body: `Questions about these terms: ${CONTACT.email} or ${CONTACT.phone}.`,
  },
];

export default function TermsOfServicePage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <Link
        href="/"
        className="text-muted-foreground hover:text-foreground inline-flex items-center gap-1.5 text-sm transition-colors"
      >
        <ArrowLeft className="size-4" /> Back to coldop.in
      </Link>

      <h1 className="mt-6 text-3xl font-bold tracking-tight sm:text-4xl">Terms of Service</h1>
      <p className="text-muted-foreground mt-2 text-sm">Last updated: 29 July 2026</p>

      <div className="mt-10 space-y-8">
        {sections.map((section) => (
          <section key={section.heading}>
            <h2 className="text-lg font-semibold">{section.heading}</h2>
            <p className="text-muted-foreground mt-2 leading-relaxed text-pretty">{section.body}</p>
          </section>
        ))}
      </div>
    </main>
  );
}
